### ISSUE TITLE
Origin of these files, more designs?

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/mathcad_Final_Designs#1]
Hey @clare45, uploader of this repo, what's the origin of these files? Were they taken from teamforge? If so, were they taken from [here](https://forge.cornell.edu/integration/viewvc/viewvc.cgi/Final%20Designs/?root=automated_design&system=exsy1001) or the design server computer in Monroe's office? 

@monroews 
1. Do we want to have any more final designs  ready and made before teamforge is decomissioned? 
1. Once that happens, will the [design server](http://designserver.cee.cornell.edu/Designs/) still exist and function?
1. When you pushed a change to the teamforge repo via SVN a few weeks ago, was that change automatically made to the [design server](http://designserver.cee.cornell.edu/Designs/)? That is to say, when using references in Mathcad, can I simply make a reference to the design server or must it be local?

**Comment by monroews** [comment]
I created [designs from 12 - 60 L/s](http://designserver.cee.cornell.edu/Designs/EtFlocSedFi/Index.html).

I was not able to get viable designs between for the single sed tank low flow plants.

The design server will continue to function as a website. The design engine will likely not be able to make new designs using any methods because it will be throwing errors from not being able to get code from team forge. That means that we will be limited to the work flow where we create a design in Mathcad and then copy and paste the command line code into AutoCAD.

We will not have access to different versions of the source code.  Is it worth trying to get different versions? My current assumption is that if we need a small plant that it will need to be with OnShape.

**Comment by juanchon998** [comment]
I'm not sure if we want to have different version! I just wanted to know exactly how the decommission would affect things and make sure again that we were ready for it.

**Comment by clare45** [comment]
If it is till relevant they were downloaded from teamforge onto a lab computer and then uploaded to here

**Comment by juanchon998** [comment]
Thank you! 3 files beginning with the letter `M` were not transferred over, but I put pushed them in last week. :Mathcad:

**Comment by eak24** [comment]
This is now created and uploaded here. To find a particular SVN version commit hash, use `git log --all --grep='design@4921'` where 4921 is the revision you want to find. That should return something like:

```
commit cbd1eee3eb3ea337458cf2a35bd877da92025ce4
Author: mw24 <mw24@d22a8b0d-b447-0410-a14f-ca4c0a428a39>
Date:   Thu May 17 13:58:47 2012 +0000

    git-svn-id: https://forge.cornell.edu/svn/repos/automated_design@4921 d22a8b0d-b447-0410-a14f-ca4c0a428a39
```

So now if you want to checkout that version, plug in `git checkout cbd1eee3eb3ea337458cf2a35bd877da92025ce4`
